lib_arm/board.c: fix reference to getenv_IPaddr
In commit 6ac59c5518e1d2e2ef1c4b8dee99267dfbdf9cdc
The changes in net/Makefile and net/net.c cause
	lib_arm/board.c:360: undefined reference to `getenv_IPaddr'
since net.c is now not compiled at all if CONFIG_CMD_NET is not set.
Previously net.c:getenv_IPaddr() was always compiled, i.e. not embraced by
ifdef CONFIG_CMD_NET.

Do use getenv_IPaddr only if CONFIG_CMD_NET is set.